services:
  #  nextjs:
  #    build:
  #   context: .
  #   dockerfile: Dockerfile
  # ports:
  #   - "3000:3000"
  # environment:
  #   - NODE_ENV=production
  #   - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
  # depends_on:
  #   - db

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: